# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      days: 45

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - id: days
        run: |
          echo "days=${days}" >> "$GITHUB_OUTPUT"

      - name: find issues past ${{ env.days }} days
        run: echo "${{ steps.days.outputs.days }}"

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 1170300
          private-key: ${{ secrets.PRIVATE_KEY }}
      - name: query graphql for project
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: | 
          gh api graphql -f query='
            query{
              organization(login: "joshjohanning-org"){
                projectV2(number: 24) {
                  id
                }
              }
            }'

            gh project item-list 24 --owner "joshjohanning-org"
